### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by kesevone** [alitoufighi/tg-auto-reaction#1] opened 2022-10-18 15:00 UTC
hi, when I try to run the script, I get this message: 
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from client import app
  File "D:\Users\soz\testing\client.py", line 7, in <module>
    api_id = int(os.getenv('myapiid'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

api_id = int(os.getenv('myapiid'))
api_hash = os.getenv('myapihash')

**Comment by alitoufighi** [comment] 2022-10-18 15:04
Hi!
This `os.getenv('API_ID')` (in `client.py`) is used to fetch `api_id` from an environment variable, so that you can set it upon running without changing the code.

If you want to hardcode your `api_id`, and `29690615` is your `api_id`, simply set its value like this:
```
api_id = 29690615
```

**Comment by alitoufighi** [comment] 2022-10-18 15:06
What I said also goes for your `api_hash`.

Also, since these values are important ones, I suggest you to remove them from your comment here or if possible, revoke them in your telegram panel (I don't know if it's possible). Somebody can use these values to impersonate you.

**Comment by keygone** [comment] 2022-10-18 15:07
ok but now I'm getting a syntax error 
![image](https://user-images.githubusercontent.com/70077088/196469598-d8323f55-04be-43b6-b6c8-55f64fd6f027.png)

**Comment by kesevone** [comment] 2022-10-18 15:24
![fsd](https://user-images.githubusercontent.com/70077088/196474013-3f7eab31-85a9-4f43-aba2-bb05ef631afc.png)
![fsdag](https://user-images.githubusercontent.com/70077088/196474140-cf856dc9-b7be-4cd6-8a25-4f63a24fe05e.png)

I did everything, but he doesn't put a reaction, sorry, I don't understand a little

**Comment by kesevone** [comment] 2022-10-18 15:29
in victim and groups, I specified the id of the person to whom he will put the reactions

**Comment by alitoufighi** [comment] 2022-10-18 15:30
That's fine. Are you getting an exception or any logs?
Did you log into your account when first prompted?

**Comment by alitoufighi** [comment] 2022-10-18 15:34
> in victim and groups, I specified the id of the person to whom he will put the reactions

That `group_ids` is used to limit reactions to a group. Group id is different than user id. If you are setting both of them to the same value, I think you're doing something wrong.
You can try removing group id to see whether it works at all. Remove line 16 (`filters.chat(list(map(int, group_ids.split(',')))) &`) and that `if` condition that raises an exception when `group_ids` is not set.

**Comment by kesevone** [comment] 2022-10-18 15:39
thank you very much!! I've been looking for this code for a very long time) thank you again

**Comment by kesevone** [comment] 2022-10-18 15:39
its work

**Comment by alitoufighi** [comment] 2022-10-18 15:42
Wow! Great
Have fun!

**Comment by alitoufighi** [comment] 2022-10-18 15:42
I'll close this issue then.

**Closed as completed by alitoufighi** 2022-10-18 15:42 UTC

**Comment by kesevone** [comment] 2022-10-18 15:53
can I use the user's nickname instead of the id?

**Comment by alitoufighi** [comment] 2022-10-18 16:00
No, unfortunately.
I don't know why telegram doesn't allow this though.
I know we can use usernames for channels, but not for users.

**Comment by kesevone** [comment] 2022-10-18 16:10
can I put my own emoji? when I try to change it, it gives me an error
![image](https://user-images.githubusercontent.com/70077088/196485066-a29c6025-5f35-4064-a330-cc1eeede287c.png)

**Comment by alitoufighi** [comment] 2022-10-18 16:14
If you don't have Telegram Premium, you can put any valid emojis that are available to free users.
If you do, I think you can put any emoji you want.

**Comment by kesevone** [comment] 2022-10-18 16:20
> If you don't have Telegram Premium, you can put any valid emojis that are available to free users. If you do, I think you can put any emoji you want.

I tried and it gives me this error, even if I use regular emojis
![image](https://user-images.githubusercontent.com/70077088/196487038-7e59d49a-dd5e-4c77-87df-89ba3e5cdfa4.png)

**Comment by alitoufighi** [comment] 2022-10-18 16:23
This emoji is not in the set of free emojis. These are only the available ones:

> You can use the following emoji reactions in the free version of Telegram:
> 
>     Thumbs up 👍
>     Thumbs down 👎
>     Red heart ❤️
>     Fire 🔥
>     Smiling face with 3 hearts 🥰
>     Clap 👏
>     Big smile 😁
>     Thinking face 🤔
>     Exploding head 🤯
>     Face screaming in fear 😱
>     Abusing face 🤬
>     Crying face 😢
>     Party popper 🎉
>     Star-struck 🤩
>     Vomiting face 🤮
>     Poop emoji 💩
>     Praying/Namaste emoji 🙏

According to https://www.idownloadblog.com/2021/12/31/telegram-emoji-reactions-update/

**Comment by keygone** [comment] 2022-10-20 11:48
probably the last question, can I make several emojis at once? I have telegram premium

**Comment by PawiX25** [comment] 2024-02-10 00:18
Hey. despite having Telegram Premium. It keeps showing me an error message: Telegram says: [400 REACTION_INVALID] - Invalid reaction provided (only valid emoji are allowed) (caused by "messages.SendReaction"), even when I haven't altered the code at all, or when I'm trying to use the simple smiley face emoji. Any ideas?
